batch_size: 32
epochs: 300
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 1
weight_decay: 1e-4
fp16_precision: True

model:
  out_dim: 256
  base_model: "resnet18"
  pretrained: False

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 4
  valid_size: 0.20

loss:
  temperature: 0.5
  use_cosine_similarity: True
